apiVersion: apps/v1
kind: Deployment
metadata:
  name: amit-counter-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amit-counter
  template:
    metadata:
      labels:
        app: amit-counter
    spec:
      containers:
      - name: amit-counter
        image: amitnd/counter-service:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "DB_HOST_PLACE_HOLDER"
        - name: DB_USER
          value: "DB_USER_PLACE_HOLDER"
        - name: DB_PASSWORD
          value: "DB_PASSWORD_PLACE_HOLDER"
        - name: DB_NAME
          value: "DB_NAME_PLACE_HOLDER"