apiVersion: v1
kind: Service
metadata:
  name: amit-counter-service
  namespace: $(NAMESPACE)
spec:
  selector:
    app: amit-counter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer