name: Deploy to EKS

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      EKS_CLUSTER_NAME: ${{vars.EKS_CLUSTER_NAME}}
      AWS_REGION: ${{vars.AWS_REGION}}
      DATABASE_ENDPOINT: ${{vars.DATABASE_ENDPOINT}}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        IMAGE_DATE=$(date +%Y%m%d%H%M%S)
        docker build -t ${{ secrets.DOCKER_USERNAME }}/counter-service:latest .
        
    - name: Tag Docker image
      run: |
        docker image tag ${{ secrets.DOCKER_USERNAME }}/counter-service:latest ${{ secrets.DOCKER_USERNAME }}/counter-service:${IMAGE_DATE}

    - name: Push Docker image
      run: |
        docker image push --all-tags ${{ secrets.DOCKER_USERNAME }}/counter-service
